### ISSUE TITLE
Installing tensordict in SD Webui reinstalls torch on CPU

### ISSUE THREAD

**Issue by PladsElsker** [s1dlx/meh#51]
If I understand correctly, this project is not meant to be transformed into an extension for A1111 Webui itself, but it is meant to help extension makers by providing more merging methods. If that's the case, am I right to think that we should be able to run `pip install -r requirements.txt` in A1111 Webui's venv? 

I have torch 2.0.1+cu118 already installed, but installing tensordict reinstalls torch even if it's already installed. Is this expected? 

If I were to use this for an extension, users would get the typical "torch is not installed on the cpu" error after a restart.

**Comment by Enferlain** [comment]
You should be able to use it with its own or with the webui's venv. I haven't encountered the issue with tensordict yet. 

Try installing tensordict first, or alternative versions from here https://pypi.org/project/tensordict/#history

This extension isn't actively being developed, the author is on hiatus right now. There are various forks that people are maintaining for their use cases. There is also another fork/project being worked on called sd-mecha, but it's like a day or 2 old.

You can try sd.next, because their implementation of meh is currently the most fleshed out and integrated, but it means using sd.next so if you're not into that forks are your best luck.

**Comment by John-WL** [comment]
Ok, `tensordict==0.3.0` is only compatible with `torch>=2.1.0` apparently, but I'm using `torch==2.0.1`. Installing `tensordict==0.2.1` seems to not inadvertently reinstall torch on cpu. 

`tensordict==0.3.0` is 1 month old, this is probably why. Pinning the version in `requirements.txt` should fix this.

**Comment by John-WL** [comment]
Oh you can manage the versioning in the install.py file in A1111 Webui, so I guess it's not an issue anymore. 
Thank you for the recommendations.
